# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 'ğŸ˜Š Bio'
    url: /
    weight: 10 # è¿™é‡Œæƒé‡å€¼ä»£è¡¨æ’åº
  - name: 'ğŸ“œ Publications'
    url: /#papers
    weight: 20
  - name: 'ğŸ… Awards'
    url: /#awards
    weight: 30
  - name: 'ğŸ“’ Working Papers'
    url: /#workings
    weight: 40

  # - name: Experience
  #   url: experience/
  #   weight: 20
  # - name: Projects
  #   url: projects/
  #   weight: 30
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
